import type { SiteDictionary } from "@/lib/site";

export const en: SiteDictionary = {
  localeName: "English (UK)",
  common: {
    nav: {
      home: "Home",
      systems: "Systems",
      sdlc: "Agentic SDLC",
      workflows: "Workflows",
      automation: "Automation",
      tooling: "AI Tooling",
      lab: "Lab",
      notes: "Field Notes",
      about: "About",
      contact: "Contact",
    },
    tags: {
      home: "HOME",
      systems: "SYSTEMS",
      sdlc: "SDLC",
      workflows: "WORKFLOWS",
      automation: "AUTOMATION",
      tooling: "TOOLING",
      lab: "LAB",
      notes: "NOTES",
      about: "ABOUT",
      contact: "CONTACT",
    },
    menu: "MENU",
    close: "CLOSE",
    map: "LATTICE",
    loading: "Loading the next region",
    language: "Language",
    skipContent: "Skip to content",
    primaryNavigation: "Primary navigation",
    mobileNavigation: "Mobile navigation",
    introduction: "Introduction",
    current: "CURRENT",
    visited: "VISITED",
    mapHint: "YOU ARE AT THE BRIGHT NODE · VISITED REGIONS STAY LIT",
    menuHint: "ONE SYSTEM · VISITED REGIONS STAY LIT",
    footerSystem: "ONE SYSTEM",
    footerExplored: "OF 10 REGIONS EXPLORED",
    introStatement: ["ENGINEERING WITH AGENTS.", "BUILDING SYSTEMS THAT WORK."],
    introV2Statement: "NOTHING WORKS ALONE.",
    enter: "ENTER THE LATTICE",
    skipIntro: "Skip intro",
  },
  home: {
    metaTitle: "Eduardo Neto | Agentic Software Engineering",
    metaDescription:
      "Senior software engineer designing reliable agentic workflows, automation systems and real products with Codex, Claude and deterministic controls.",
    socialRole: "Agentic Software Engineering",
    regionLabel: "Current work",
    kicker: "THE LATTICE",
    hero: [
      "Software engineering is changing.",
      "The difficult part is no longer generating code.",
      "It is designing the system around the agents.",
    ],
    supporting:
      "Exploring how Codex, Claude and automation combine into reliable software-development workflows, and applying those methods to real products.",
    ctas: ["Explore the systems", "See the workflows", "Read the field notes"],
    cards: [
      {
        label: "ACTIVE · LIVE",
        tone: "cyan",
        live: true,
        title: "FoundMyPro",
        body: "A UK local-services discovery platform. Growth, search authority and affiliate revenue first - subscriptions later, if ever.",
        link: "Enter the cluster →",
        target: "systems",
      },
      {
        label: "ACTIVE · PRE-LAUNCH",
        tone: "amber",
        live: true,
        title: "Sentinel for Sentry",
        body: "A mobile companion for Sentry: focused alerts and informed triage away from the desk. Deliberately unlaunched while liability protections mature.",
        link: "Enter the cluster →",
        target: "systems",
      },
      {
        label: "FEATURED WORKFLOW",
        tone: "muted",
        title: "Research → Plan → Challenge → Implement → Review",
        body: "The default operating pattern: no agent writes production code before its plan has survived an adversarial challenge.",
        link: "Follow the route →",
        target: "workflows",
      },
      {
        label: "LATEST FIELD NOTE",
        tone: "muted",
        title: "The cheapest agent is a bash script",
        body: "Where the automation continuum actually pays: replacing an agent loop with forty lines of deterministic shell.",
        link: "Read in Field Notes →",
        target: "notes",
      },
    ],
    connectionLabel: "HOW IT CONNECTS",
    connectionBody:
      "Products generate engineering problems. Problems become workflows. Workflows harden into automation. What the work teaches becomes field notes - and the notes route back into the products. Open the",
    mapLink: "lattice",
    availability:
      "Quietly open to conversations about senior engineering roles and product collaborations where agentic workflows matter.",
    contactLink: "Open a connection",
  },
  systems: {
    legendLabel: "Status legend",
    kicker: "SYSTEMS",
    title: "Built in the Real World",
    intro:
      "Products as evolving systems, not case-study trophies. Each cluster holds the product, its architecture, the agents that work on it, the automation around it, the commercial model, and the questions still open.",
    legend: ["LIVE", "IN DEVELOPMENT", "EXPERIMENTAL", "PLANNED"],
    foundMyPro: {
      status: "LIVE",
      intro:
        "Most local search is built around premises: a pin on a map, an address, opening hours. That works for shops - and fails the mobile professionals who come to you. A plumber, mobile hairdresser or dog groomer with no storefront is nearly invisible in map-based tools, which surface the traditional in-store options instead. FoundMyPro exists to give these come-to-you professionals a place of relevance online: structured provider and service data organised around where they work rather than where they sit, strong local search, and an affiliate model that earns from connections rather than charging providers before the platform has proven its value.",
      facets: [
        {
          tag: "THE PROBLEM",
          body: "Conventional discovery tools assume a business has premises. Mobile professionals who travel to the customer often have no address to anchor a map listing, so searches return in-store options while the come-to-you providers stay invisible.",
        },
        {
          tag: "DISCOVERY & SEARCH",
          body: "Search-first UX: structured service taxonomies, location-aware queries, and pages designed to answer the question a searcher actually typed.",
        },
        {
          tag: "PROVIDER & SERVICE DATA",
          body: "The real asset. Structured, verified provider and service data - most engineering effort goes into acquisition, normalisation and freshness.",
        },
        {
          tag: "LOCAL SEO",
          body: "Programmatic local pages built for genuine usefulness first, rankings second. Search authority is the growth engine, so quality thresholds are strict.",
        },
        {
          tag: "AFFILIATE MONETISATION",
          body: "Revenue from connecting demand to providers via affiliate partnerships - chosen over subscriptions to keep incentives aligned with users while the platform earns trust.",
        },
        {
          tag: "AUTOMATION",
          body: "Data pipelines, page generation, freshness checks and rank monitoring are automated; agents assist with content quality review under human sampling.",
        },
        {
          tag: "PRODUCTION DECISIONS",
          body: "Boring, reliable infrastructure. Every architectural choice is weighed against being one person operating a real platform.",
        },
        {
          tag: "TRADE-OFFS",
          body: "Ambition versus resources versus speed, decided weekly. The platform grows by compounding data quality, not by feature count.",
        },
      ],
      openQuestions: {
        title: "OPEN QUESTIONS",
        body: "How far affiliate revenue scales before provider-side products make sense. Whether programmatic local pages hold rankings as search itself becomes answer-driven.",
      },
      lessons: {
        title: "LESSONS",
        body: "Operating a real platform disciplines ambition: every feature competes with data quality work, and data quality usually wins. Speed came from cutting scope, not adding agents.",
      },
    },
    sentinel: {
      status: "PRE-LAUNCH",
      intro:
        "A mobile companion for software teams that need a clear view of production when they are away from a desk. It turns selected Sentry events into focused alerts, brings the evidence needed for a first assessment onto the phone, and supports deliberate triage without trying to replace Sentry or a paging platform.",
      facets: [
        {
          tag: "INTENDED PROBLEM",
          body: "Production issues do not wait for an engineer to be at a desk. The normal Sentry workflow is desk-centred, while mobile notifications alone rarely provide enough context to make a sound decision. Sentinel is intended to close that gap between awareness and informed triage.",
        },
        {
          tag: "SYSTEM CONCEPT",
          body: "Selected Sentry events become push alerts. From the app, an engineer can see whether a workspace is calm or needs attention, inspect issue details, stack traces, tags and activity signals, then resolve, archive, snooze or continue in Sentry. The human remains in control.",
        },
        {
          tag: "RISK & RELIABILITY",
          body: "Sentinel sits beside a production monitoring workflow, where duplicate alerts, stale state or false confidence can be harmful. Its design treats notifications as hints and Sentry as authoritative, minimises data sent to devices, suppresses duplicates, retries carefully and degrades towards silence and reconciliation when certainty is lost.",
        },
        {
          tag: "LEGAL & BUSINESS CONSTRAINTS",
          body: "Connecting a workspace can involve Sentry credentials, device identifiers and customer-controlled issue data. That creates serious security, privacy, support and contractual responsibilities. Sentinel is therefore positioned as a best-effort companion for awareness and triage, not a guaranteed pager, primary monitor or autonomous incident-response system.",
        },
        {
          tag: "WHY IT ISN'T LAUNCHED",
          body: "The main launch blocker is not a missing feature. It is personal liability. I am not prepared to accept customers while a missed notification, security failure or data incident could expose me directly. Launch requires an appropriate legal entity, suitable insurance and legally reviewed protections before that risk is responsible to take.",
        },
      ],
    },
    honesty:
      "No invented metrics, customers or revenue appear on this page. Numbers arrive when they exist.",
  },
  sdlc: {
    kicker: "AGENTIC SDLC",
    title: "Engineering the Workflow",
    intro:
      'Agentic development is not "ask AI to build the app". It is the deliberate design of context, constraints, permissions, feedback loops, checkpoints, independent verification, escalation rules and ownership across the whole lifecycle, without surrendering engineering judgement.',
    selector: "THE LIFECYCLE AS A CONNECTED SYSTEM · SELECT A STAGE",
    responsibility: "WHO HOLDS RESPONSIBILITY HERE",
    actors: [
      "HUMAN",
      "IMPLEMENTATION AGENT",
      "REVIEW AGENT",
      "RESEARCH AGENT",
      "TESTING / VALIDATION",
      "CI/CD & PRODUCTION",
    ],
    stages: [
      { label: "DISCOVERY", name: "Discovery", detail: "Framing the problem before any agent sees it. Agents help survey prior art and competitors; the decision of what is worth building stays human.", weights: [3, 0, 0, 2, 0, 0] },
      { label: "REQUIREMENTS", name: "Requirements", detail: "Agents draft and stress-test requirements against edge cases; the human owns priorities and the definition of done.", weights: [3, 1, 1, 2, 0, 0] },
      { label: "RESEARCH", name: "Research", detail: "The research agent explores libraries, patterns and constraints in a sandbox. Findings are treated as leads, not facts, until verified.", weights: [1, 0, 1, 3, 0, 0] },
      { label: "ARCHITECTURE", name: "Architecture", detail: "Agents propose and criticise structures; the human chooses, because architecture is where agents most confidently optimise locally.", weights: [3, 1, 2, 1, 0, 0] },
      { label: "PLANNING", name: "Planning", detail: "Work is decomposed into agent-sized, independently verifiable steps with explicit permissions and stop conditions.", weights: [3, 2, 1, 0, 0, 0] },
      { label: "CODING", name: "Coding", detail: "The primary implementation agent works inside a scoped context with named files it may touch. Everything else is off-limits by default.", weights: [1, 3, 0, 0, 1, 0] },
      { label: "TESTING", name: "Testing", detail: "Tests are written or approved before implementation where risk justifies it; a separate loop validates rather than trusting the author agent.", weights: [1, 1, 1, 0, 3, 1] },
      { label: "REVIEW", name: "Review", detail: "An independent review agent, with no memory of the implementation conversation, reads the diff cold. The human arbitrates disagreements.", weights: [2, 0, 3, 0, 1, 0] },
      { label: "DEBUGGING", name: "Debugging", detail: "Reproduction before repair: no fix is accepted until the failure is demonstrated, then demonstrated fixed.", weights: [2, 2, 1, 1, 2, 0] },
      { label: "SECURITY", name: "Security", detail: "Agents scan and suggest; a human plus deterministic tooling own the final judgement. This is a place agents fail quietly.", weights: [3, 0, 2, 1, 2, 1] },
      { label: "DOCUMENTATION", name: "Documentation", detail: "Documentation doubles as executable context for future agent sessions, written for the next agent as much as the next human.", weights: [1, 2, 1, 0, 0, 0] },
      { label: "DEPLOYMENT", name: "Deployment", detail: "Deterministic pipelines, not agents, move code. Agents prepare release notes and readiness checks; CI/CD holds the keys.", weights: [2, 0, 0, 0, 1, 3] },
      { label: "MONITORING", name: "Monitoring", detail: "Production feedback closes the loop. Errors and metrics become structured context that routes back into planning.", weights: [2, 0, 0, 1, 1, 3] },
      { label: "MAINTENANCE", name: "Maintenance", detail: "Dependency updates and small fixes are the safest agent territory: bounded, verifiable, reversible.", weights: [1, 3, 1, 0, 2, 1] },
      { label: "RETROSPECTIVES", name: "Retrospectives", detail: "What did the agents get wrong, and was it predictable? Failure patterns feed the workflow library.", weights: [3, 0, 1, 1, 0, 1] },
    ],
    failuresTitle: "WHERE AGENTS FAIL",
    failuresIntro:
      "The workflow exists because these failure modes are predictable. Each one is a terminated path in the lattice: observed, named, and designed around.",
    mitigation: "MITIGATION",
    flipFor: "Flip for mitigation",
    flipBack: "Flip back",
    failures: [
      { name: "Confident invention", problem: "APIs, flags and behaviours that never existed, delivered with total certainty.", fix: "Verify against real sources: documentation, code and running systems, never against the agent's memory. Claims without evidence are leads, not facts." },
      { name: "Shallow architecture", problem: "Structures that satisfy the prompt but ignore the system around them.", fix: "Adversarial architecture review before any code: a second agent, or the human, attacks the proposal until it accounts for the whole system." },
      { name: "Local optimisation", problem: "Improving the file at the expense of the codebase.", fix: "Explicit scope in every task, plus a reviewer instructed to read beyond the diff and check the consumers of what changed." },
      { name: "Context loss", problem: "Long sessions silently forget earlier constraints.", fix: "Short, scoped sessions with deliberate handover documents. Compress context on purpose before the agent loses it by accident." },
      { name: "Unnecessary rewrites", problem: "Rewriting working code because rewriting is easier than reading.", fix: "Write permissions on named files only. Everything else is read-only by default. Rewriting must be requested, never assumed." },
      { name: "Incomplete verification", problem: '"Tests pass" because the tests were weakened until they passed.', fix: "Independent validation the author agent cannot touch: separate test runs, protected test files, and a reviewer who diffs the tests too." },
      { name: "Excessive tool usage", problem: "Ten tool calls where one grep would do: cost, noise and latency.", fix: "Observe traces regularly and prune the workflow. Give agents cheaper deterministic shortcuts and instructions on when to use them." },
      { name: "Hidden coupling", problem: "Changes that work locally and break a consumer nobody mentioned.", fix: "Repository onboarding docs and dependency maps as standing context, so every session knows what depends on what before it edits." },
      { name: "Security mistakes", problem: "Secrets in logs, permissive defaults, injection-friendly string building.", fix: "Deterministic scanning plus human review on every security-relevant change. Agent self-assessment is never accepted as evidence." },
      { name: "Agreeing with flawed assumptions", problem: "The user is wrong and the agent politely proceeds anyway.", fix: "An explicit challenge step whose only job is disagreement: an agent prompted to find what is wrong, not to be helpful." },
    ],
  },
  workflows: {
    kicker: "WORKFLOWS",
    title: "Agent Operating Patterns",
    intro:
      "A library of reusable patterns. Each defines the problem, the routing of work between human and agents, how the output is validated, and, as importantly, when not to use it.",
    featureLabel: "PATTERN 01 · FULLY DEVELOPED",
    featureTitle: "Research → Plan → Challenge → Implement → Review",
    stages: ["RESEARCH", "PLAN", "CHALLENGE", "IMPLEMENT", "REVIEW"],
    fields: [
      { tag: "PROBLEM", body: "Agents produce plausible code immediately, which makes it tempting to skip thinking. Unchallenged plans embed wrong assumptions that surface as expensive rework." },
      { tag: "WORKFLOW", body: "A research agent surveys the territory. A planning pass produces a stepwise plan. A separate agent, or the same one adversarially prompted, attacks the plan. Only a surviving plan reaches implementation. A cold reviewer reads the final diff." },
      { tag: "HUMAN RESPONSIBILITY", body: "Frame the problem, judge the challenge round, arbitrate disagreements, approve the plan, and own the merge. The human is the constant across every stage." },
      { tag: "AGENT RESPONSIBILITY", body: "Research breadth, plan drafting, adversarial critique, implementation within scope, and an independent cold-context review." },
      { tag: "VALIDATION", body: "The challenge round validates the plan; tests and independent review validate the code. Nothing merges on the implementer's word alone." },
      { tag: "RISKS", body: "Ceremony on trivial tasks; challenge rounds that degrade into agreement if the critic shares the planner's context; humans rubber-stamping surviving plans." },
      { tag: "WHEN NOT TO USE", body: "Small, reversible, well-understood changes. A one-line fix does not need a five-stage pipeline. That is what maintenance patterns are for." },
    ],
    notWhen: "NOT WHEN",
    patterns: [
      { number: "02", name: "Architect / Builder separation", problem: "One agent designing and implementing defends its own design. Splitting the roles keeps structure honest.", notWhen: "The structure is already fixed and the work is filling in a known shape." },
      { number: "03", name: "Independent code-review agent", problem: "A reviewer with no memory of the implementation reads the diff cold and reports findings before any human review.", notWhen: "Generated throwaway code that will never reach production." },
      { number: "04", name: "Test-first agent loop", problem: "Tests written and approved before implementation give the agent an objective target and the human a verification anchor.", notWhen: "Exploratory work where the desired behaviour is still being discovered." },
      { number: "05", name: "Bug reproduction before repair", problem: 'No fix is accepted until the failure is demonstrated, then demonstrated fixed. Kills "it should work now".', notWhen: "Truly non-deterministic failures. Then the pattern shifts to instrumentation first." },
      { number: "06", name: "Documentation as executable context", problem: "Docs written so a fresh agent session can act on them: onboarding material that is tested, not assumed.", notWhen: "Fast-moving prototypes where docs would immediately rot." },
      { number: "07", name: "Repository onboarding", problem: "A structured first session that maps the codebase, conventions and coupling before any agent is allowed to change it.", notWhen: "Repositories small enough to fit in a single context window." },
      { number: "08", name: "Context compression & handover", problem: "Long tasks are split across sessions with deliberate handover documents, because context loss is silent and cumulative.", notWhen: "Tasks that comfortably finish inside one focused session." },
    ],
  },
  automation: {
    kicker: "AUTOMATION",
    title: "Remove the Repetition",
    intro:
      "Scripts, tools and small systems that eliminate repetitive engineering work. Two rules govern everything here: automation is a continuum, and not every task deserves an agent. A deterministic script is often cheaper, safer and better.",
    continuum: [
      { label: "MANUAL", body: "Done by hand. Correct default for anything done fewer than three times." },
      { label: "ASSISTED", body: "A human drives; tooling or an agent accelerates the boring middle." },
      { label: "SCRIPTED", body: "Deterministic, versioned, reviewable. The workhorse tier: most tasks should stop here." },
      { label: "AGENT-OPERATED", body: "An agent executes a procedure that occasionally needs judgement mid-run." },
      { label: "CONDITIONALLY AUTONOMOUS", body: "Runs unattended within hard limits, with escalation rules and a kill switch. Earned, never assumed." },
    ],
    items: [
      { name: "Repository analysis", tier: "AGENT-OPERATED", body: "Maps structure, conventions and coupling into an onboarding brief for humans and agent sessions alike." },
      { name: "Environment validation", tier: "SCRIPTED", body: "One command that proves a development environment is actually complete before work begins." },
      { name: "Test orchestration", tier: "SCRIPTED", body: "Selects and runs the right test subset per change, with full runs gated to merges." },
      { name: "Deployment checks", tier: "SCRIPTED", body: "Pre-flight and post-deploy verification. Deterministic on purpose: no judgement wanted here." },
      { name: "Dependency monitoring", tier: "AGENT-OPERATED", body: "Watches updates and advisories, drafts upgrade branches, and files the evidence for a human decision." },
      { name: "Documentation generation", tier: "AGENT-OPERATED", body: "Keeps executable context current from code and commit history, sampled by a human." },
      { name: "Visual regression", tier: "SCRIPTED", body: "Screenshot diffs on key flows. Cheap, dumb, and catches what unit tests structurally cannot." },
      { name: "Issue triage", tier: "AGENT-OPERATED", body: "Clusters, deduplicates and enriches incoming issues; priority remains a human call." },
      { name: "Agent handovers", tier: "AGENT-OPERATED", body: "Generates compressed context documents when a task must cross session boundaries." },
      { name: "Operational reporting", tier: "SCRIPTED", body: "Weekly platform health summaries assembled from logs and metrics. A cron job, not an agent." },
    ],
  },
  tooling: {
    kicker: "AI TOOLING",
    title: "Value per Subscription",
    intro:
      'Getting the most from Codex, Claude and similar subscriptions without brand worship. The useful question is not "which model is best" but which role each tool plays in a workflow, and when a local script makes the whole question moot.',
    selector: "ROLES, NOT RANKINGS · SELECT A ROLE",
    discipline: "DISCIPLINE",
    roles: [
      { label: "EXPLORER", name: "Explorer", body: "Surveys unfamiliar territory: codebases, libraries, APIs, prior art. Optimised for breadth and cheap iteration, not correctness.", discipline: "Everything the explorer reports is a lead until verified. Never let exploration output flow directly into implementation." },
      { label: "ARCHITECT", name: "Architect", body: "Proposes structures, interfaces and trade-offs. Best used adversarially: one architect proposes, another challenges.", discipline: "The human picks. Agents will defend whichever architecture they generated first." },
      { label: "IMPLEMENTER", name: "Implementer", body: "Writes code inside a scoped context: named files, explicit permissions, a plan that already survived challenge.", discipline: "Scope is the control surface. An implementer with repository-wide write access is a liability, not a productivity gain." },
      { label: "REVIEWER", name: "Reviewer", body: "Reads diffs cold, with no memory of the implementation conversation, and reports findings independently.", discipline: "Independence is the entire value. A reviewer that shares context with the implementer just agrees with it." },
      { label: "DEBUGGER", name: "Debugger", body: "Reproduces failures, forms hypotheses, and tests them one at a time. Reproduction before repair, always.", discipline: 'Refuse fixes for bugs that were never demonstrated. "It should work now" is not evidence.' },
      { label: "DOCS PARTNER", name: "Documentation partner", body: "Maintains docs as executable context: the onboarding material the next agent session will actually consume.", discipline: "Docs an agent cannot act on are decoration. Test them by starting a fresh session from nothing but the docs." },
      { label: "BROWSER OPERATOR", name: "Browser operator", body: "Drives a real browser for verification: flows, forms, visual states, regressions a unit test cannot see.", discipline: "Use for verification, not discovery. It is slow and expensive per finding." },
      { label: "AUTOMATION RUNNER", name: "Automation runner", body: "Executes scripted procedures where a judgement call may occasionally be needed mid-run.", discipline: "If no judgement is ever needed, delete the agent and keep the script." },
    ],
    designer: "WORKFLOW DESIGNER · A CONCEPTUAL TOOL",
    caveat:
      "Slide the characteristics of a task; the recommendation describes workflow shape, not prices or capabilities. Where live data would be needed, this stays deliberately conceptual. Check current subscription limits before relying on any cost assumption.",
    sliderLabels: ["COMPLEXITY", "RISK", "REPETITION", "COST SENSITIVITY", "VERIFICATION NEEDED"],
    levels: ["MINIMAL", "LOW", "MODERATE", "HIGH", "CRITICAL"],
    recommendation: "RECOMMENDED SHAPE",
    recommendations: {
      script: { title: "Deterministic script", lines: ["High repetition with low complexity and low risk is script territory. An agent here adds cost and nondeterminism.", "Write it once, version it, and let CI run it."] },
      highRisk: { title: "Human-anchored, multi-agent with gates", lines: ["High risk demands independent verification: separate implementation and review agents with no shared context.", "Insert explicit human approval gates before anything irreversible."], validation: "Add deterministic validation tooling: tests and static analysis as a third, non-negotiable check." },
      complex: { title: "Research → Plan → Challenge → Implement → Review", lines: ["High complexity earns the full pattern: research first, then a plan that must survive an adversarial challenge before code.", "Decompose into independently verifiable steps to keep context manageable."] },
      moderate: { title: "Single agent, scoped context", lines: ["Moderate task: one implementation agent with named files, a clear definition of done, and a quick human review."] },
      cost: "Cost-sensitive: route research to cheaper models and reserve the strongest model for the step where quality actually compounds.",
      repetition: "Repetition is high. After the second manual run, extract the stable parts into a script and shrink the agent's role.",
    },
  },
  lab: {
    kicker: "LAB",
    title: "Experiments in Progress",
    intro: "Unfinished by design. Discarded experiments stay visible. Knowing when to stop is part of the method.",
    items: [
      { status: "TESTING", tone: "cyan", name: "Cold-context review harness", body: "Tooling that spawns a reviewer agent with zero implementation context and diffs its findings against human review. Measuring where independence actually pays." },
      { status: "PROTOTYPING", tone: "cyan", name: "Handover compressor", body: "Turns a long agent session into a minimal context document a fresh session can resume from. The hard part is deciding what to forget." },
      { status: "INVESTIGATING", tone: "muted", name: "Answer-engine visibility", body: "How programmatic local pages surface in AI answer engines versus classic search. Early, mostly measurement design." },
      { status: "PAUSED", tone: "amber", name: "Visual regression via browser agent", body: "An agent operating a browser for regression checks. Paused: a screenshot-diff script does 90% of it at 5% of the cost." },
      { status: "DISCARDED", tone: "muted", discarded: true, name: "Fully autonomous dependency upgrades", body: "Discarded after two near-misses. Upgrades that pass tests can still change behaviour tests never covered. Now agent-drafted, human-merged." },
      { status: "SHIPPED", tone: "cyan", name: "Environment doctor", body: "A single script that validates a full local setup and prints exactly what is missing. Boring, and used every week." },
    ],
  },
  notes: {
    categoriesLabel: "Categories",
    kicker: "FIELD NOTES",
    title: "What the Work Teaches",
    intro: "Writing that accumulates rather than scrolls. Every note is connected to the system or workflow it came from. Follow a note back to its origin and the route lights up.",
    categories: ["AGENTIC ENGINEERING", "SOFTWARE ARCHITECTURE", "AUTOMATION", "BUILDING PRODUCTS", "AI ECONOMICS", "FAILURE ANALYSIS", "PRACTICAL EXPERIMENTS", "CAREER & CRAFT"],
    items: [
      { title: "The cheapest agent is a bash script", category: "AI ECONOMICS", origin: "AUTOMATION", target: "automation", body: "Where the automation continuum actually pays: replacing an agent loop with forty lines of deterministic shell, and how to spot the tasks where that is true." },
      { title: "What a challenge round catches", category: "AGENTIC ENGINEERING", origin: "WORKFLOWS", target: "workflows", body: "A month of logging every plan that failed adversarial review: wrong assumptions about data shape dominate, hallucinated APIs are rarer than expected." },
      { title: "Programmatic pages without the spam", category: "BUILDING PRODUCTS", origin: "FOUNDMYPRO", target: "systems", body: "The quality thresholds that keep generated local pages genuinely useful, and what happened to the ones that missed the bar." },
      { title: "Two near-misses with autonomous upgrades", category: "FAILURE ANALYSIS", origin: "LAB", target: "lab", body: 'The dependency-upgrade experiment that got discarded: what the tests missed, and why "green" was not the same as "safe".' },
      { title: "Why Sentinel is not launched", category: "BUILDING PRODUCTS", origin: "SENTINEL", target: "systems", body: "Liability, trust and the discipline of delaying a product whose failure modes land on someone else's production system." },
      { title: "From service floor to system design", category: "CAREER & CRAFT", origin: "ABOUT", target: "about", body: "What hospitality operations teach about software: standards are behaviour under pressure, and every system is judged at its worst moment." },
    ],
  },
  about: {
    kicker: "ABOUT",
    title: "The Engineer Behind the System",
    paragraphs: [
      "Software engineer with enterprise application experience, building products on the side and treating AI-assisted development as an engineering discipline rather than a shortcut.",
      "Before software: years leading hospitality operations. That background still shows: service as a standard rather than a slogan, calm under pressure, and attention to the operational details that decide whether a system actually works for the people using it.",
      "The current focus is agentic software development: designing the context, constraints and verification around AI agents so their speed becomes reliable output. The products on this site are where those methods get tested against reality.",
    ],
    preference: "Preference: useful systems over demonstrations. If it doesn't run in production, it's a hypothesis.",
    portraitAlt: "Eduardo Neto",
    playPortraitVideo: "Play Eduardo's introduction video",
    replayPortraitVideo: "Replay Eduardo's introduction video",
    closePortraitVideo: "Close video",
    loadingPortraitVideo: "Loading video",
    errorPortraitVideo: "VIDEO UNAVAILABLE. TRY AGAIN.",
    portraitVideoLabel: "Eduardo Neto introduction video",
    portraitVideoHint: "PLAY 00:08",
  },
  contact: {
    kicker: "CONTACT",
    title: "Open a Connection",
    intro: "A message creates a new node in the lattice. Pick the edge it should attach to, or just write.",
    routes: [
      { name: "Engineering roles", body: "Senior engineering positions where agentic workflows and product thinking matter.", subject: "Engineering role" },
      { name: "Product collaboration", body: "Building something real and want a systems-minded partner.", subject: "Product collaboration" },
      { name: "Technical discussion", body: "Agentic SDLC, workflow design, automation economics. Disagreement welcome.", subject: "Technical discussion" },
      { name: "Project feedback", body: "You used FoundMyPro or read a field note and something was wrong or missing.", subject: "Project feedback" },
      { name: "Speaking or writing", body: "Talks or articles on agentic development, told from practice rather than hype.", subject: "Speaking or writing" },
    ],
    replyNote: "replies within a few days, honestly prioritised.",
  },
};
