import type { SiteDictionary } from "@/lib/site";

export const pt: SiteDictionary = {
  localeName: "Português (Portugal)",
  common: {
    nav: {
      home: "Início",
      systems: "Sistemas",
      sdlc: "SDLC com agentes",
      workflows: "Fluxos",
      automation: "Automação",
      tooling: "Ferramentas de IA",
      lab: "Laboratório",
      notes: "Notas de campo",
      about: "Sobre",
      contact: "Contacto",
    },
    tags: {
      home: "INÍCIO",
      systems: "SISTEMAS",
      sdlc: "SDLC",
      workflows: "FLUXOS",
      automation: "AUTOMAÇÃO",
      tooling: "FERRAMENTAS",
      lab: "LABORATÓRIO",
      notes: "NOTAS",
      about: "SOBRE",
      contact: "CONTACTO",
    },
    menu: "MENU",
    close: "FECHAR",
    map: "LATTICE",
    loading: "A carregar a próxima região",
    language: "Idioma",
    skipContent: "Saltar para o conteúdo",
    primaryNavigation: "Navegação principal",
    mobileNavigation: "Navegação móvel",
    introduction: "Introdução",
    current: "ACTUAL",
    visited: "VISITADO",
    mapHint: "ESTÁ NO NÓ MAIS LUMINOSO · AS REGIÕES VISITADAS FICAM ACESAS",
    menuHint: "UM SISTEMA · AS REGIÕES VISITADAS FICAM ACESAS",
    footerSystem: "UM SISTEMA",
    footerExplored: "DE 10 REGIÕES EXPLORADAS",
    introStatement: ["ENGENHARIA COM AGENTES.", "A CONSTRUIR SISTEMAS QUE FUNCIONAM."],
    enter: "ENTRAR NA LATTICE",
    skipIntro: "Saltar introdução",
  },
  home: {
    metaTitle: "A Lattice",
    regionLabel: "Trabalho actual",
    kicker: "A LATTICE",
    hero: [
      "A engenharia de software está a mudar.",
      "A parte difícil já não é gerar código.",
      "É desenhar o sistema à volta dos agentes.",
    ],
    supporting:
      "A explorar como o Codex, Claude e a automação se combinam em fluxos de desenvolvimento de software fiáveis, e a aplicar esses métodos a produtos reais.",
    ctas: ["Explorar os sistemas", "Ver os fluxos", "Ler as notas de campo"],
    cards: [
      {
        label: "ACTIVO · EM PRODUÇÃO",
        tone: "cyan",
        live: true,
        title: "FoundMyPro",
        body: "Uma plataforma de descoberta de serviços locais no Reino Unido. Primeiro crescimento, autoridade na pesquisa e receita de afiliados - subscrições mais tarde, se alguma vez fizerem sentido.",
        link: "Entrar no grupo →",
        target: "systems",
      },
      {
        label: "ACTIVO · PRÉ-LANÇAMENTO",
        tone: "amber",
        live: true,
        title: "Sentinel for Sentry",
        body: "Um complemento móvel para o Sentry: alertas focados e triagem informada longe da secretária. Deliberadamente por lançar enquanto amadurecem as protecções de responsabilidade.",
        link: "Entrar no grupo →",
        target: "systems",
      },
      {
        label: "FLUXO EM DESTAQUE",
        tone: "muted",
        title: "Pesquisa → Plano → Desafio → Implementação → Revisão",
        body: "O padrão de operação por defeito: nenhum agente escreve código de produção antes de o seu plano sobreviver a um desafio adversarial.",
        link: "Seguir o percurso →",
        target: "workflows",
      },
      {
        label: "NOTA DE CAMPO MAIS RECENTE",
        tone: "muted",
        title: "O agente mais barato é um script bash",
        body: "Onde o contínuo da automação realmente compensa: substituir um ciclo de agente por quarenta linhas de shell determinístico.",
        link: "Ler nas Notas de Campo →",
        target: "notes",
      },
    ],
    connectionLabel: "COMO TUDO SE LIGA",
    connectionBody:
      "Os produtos geram problemas de engenharia. Os problemas tornam-se fluxos. Os fluxos solidificam-se em automação. O que o trabalho ensina torna-se notas de campo - e as notas regressam aos produtos. Abra a",
    mapLink: "lattice",
    availability:
      "Disponível, com discrição, para conversas sobre funções sénior de engenharia e colaborações de produto onde os fluxos com agentes sejam relevantes.",
    contactLink: "Abrir uma ligação",
  },
  systems: {
    legendLabel: "Legenda de estados",
    kicker: "SISTEMAS",
    title: "Construídos no Mundo Real",
    intro:
      "Produtos apresentados como sistemas em evolução, não como troféus de estudos de caso. Cada grupo contém o produto, a arquitectura, os agentes que nele trabalham, a automação que o rodeia, o modelo comercial e as questões ainda em aberto.",
    legend: ["EM PRODUÇÃO", "EM DESENVOLVIMENTO", "EXPERIMENTAL", "PLANEADO"],
    foundMyPro: {
      status: "EM PRODUÇÃO",
      intro:
        "A maior parte da pesquisa local está organizada em torno de instalações: um ponto no mapa, uma morada, um horário. Isso funciona para lojas - e falha com os profissionais móveis que vão até ao cliente. Um canalizador, cabeleireiro móvel ou tosquiador de cães sem loja física é quase invisível nas ferramentas baseadas em mapas, que apresentam as opções tradicionais em loja. O FoundMyPro existe para dar relevância online a estes profissionais que se deslocam ao cliente: dados estruturados de prestadores e serviços organizados por onde trabalham, não por onde estão sediados, pesquisa local forte e um modelo de afiliados que ganha com as ligações em vez de cobrar aos prestadores antes de a plataforma provar o seu valor.",
      facets: [
        {
          tag: "O PROBLEMA",
          body: "As ferramentas convencionais de descoberta assumem que uma empresa tem instalações. Os profissionais móveis que se deslocam ao cliente muitas vezes não têm uma morada para ancorar uma listagem no mapa, pelo que as pesquisas devolvem opções em loja enquanto os prestadores que vão ao cliente permanecem invisíveis.",
        },
        {
          tag: "DESCOBERTA E PESQUISA",
          body: "Experiência orientada à pesquisa: taxonomias estruturadas de serviços, consultas conscientes da localização e páginas concebidas para responder à pergunta que a pessoa realmente escreveu.",
        },
        {
          tag: "DADOS DE PRESTADORES E SERVIÇOS",
          body: "O activo real. Dados estruturados e verificados de prestadores e serviços - a maior parte do esforço de engenharia vai para aquisição, normalização e actualização.",
        },
        {
          tag: "SEO LOCAL",
          body: "Páginas locais programáticas construídas primeiro para serem genuinamente úteis e só depois para obterem classificações. A autoridade na pesquisa é o motor de crescimento, por isso os limiares de qualidade são exigentes.",
        },
        {
          tag: "MONETIZAÇÃO POR AFILIAÇÃO",
          body: "Receita por ligar procura e prestadores através de parcerias de afiliados - escolhida em vez de subscrições para manter os incentivos alinhados com os utilizadores enquanto a plataforma conquista confiança.",
        },
        {
          tag: "AUTOMAÇÃO",
          body: "Os fluxos de dados, geração de páginas, verificações de actualidade e monitorização de classificações são automatizados; os agentes ajudam a rever a qualidade do conteúdo sob amostragem humana.",
        },
        {
          tag: "DECISÕES DE PRODUÇÃO",
          body: "Infra-estrutura aborrecida e fiável. Cada escolha arquitectural é ponderada face à realidade de uma pessoa operar uma plataforma real.",
        },
        {
          tag: "COMPROMISSOS",
          body: "Ambição, recursos e velocidade, decididos todas as semanas. A plataforma cresce pela acumulação de qualidade dos dados, não pela contagem de funcionalidades.",
        },
      ],
      openQuestions: {
        title: "QUESTÕES EM ABERTO",
        body: "Até onde pode crescer a receita de afiliados antes de produtos para prestadores fazerem sentido. Se as páginas locais programáticas mantêm as classificações à medida que a própria pesquisa passa a ser orientada por respostas.",
      },
      lessons: {
        title: "LIÇÕES",
        body: "Operar uma plataforma real disciplina a ambição: cada funcionalidade compete com o trabalho de qualidade dos dados, e os dados costumam ganhar. A velocidade veio de reduzir o âmbito, não de acrescentar agentes.",
      },
    },
    sentinel: {
      status: "PRÉ-LANÇAMENTO",
      intro:
        "Um complemento móvel para equipas de software que precisam de uma visão clara da produção quando estão longe da secretária. Transforma eventos seleccionados do Sentry em alertas focados, leva para o telefone a evidência necessária para uma primeira avaliação e apoia uma triagem deliberada sem tentar substituir o Sentry ou uma plataforma de prevenção.",
      facets: [
        {
          tag: "PROBLEMA VISADO",
          body: "Os problemas de produção não esperam que um engenheiro esteja à secretária. O fluxo normal do Sentry está centrado no computador, enquanto as notificações móveis raramente fornecem contexto suficiente para uma decisão sólida. O Sentinel pretende fechar essa distância entre conhecimento e triagem informada.",
        },
        {
          tag: "CONCEITO DO SISTEMA",
          body: "Eventos seleccionados do Sentry tornam-se alertas push. Na aplicação, um engenheiro pode ver se um espaço de trabalho está calmo ou requer atenção, inspeccionar detalhes do problema, stack traces, etiquetas e sinais de actividade, e depois resolver, arquivar, adiar ou continuar no Sentry. O controlo permanece humano.",
        },
        {
          tag: "RISCO E FIABILIDADE",
          body: "O Sentinel funciona ao lado de um fluxo de monitorização de produção, onde alertas duplicados, estado desactualizado ou falsa confiança podem causar danos. O desenho trata as notificações como indícios e o Sentry como fonte autoritativa, minimiza os dados enviados para os dispositivos, suprime duplicados, repete com cuidado e degrada para silêncio e reconciliação quando perde a certeza.",
        },
        {
          tag: "RESTRIÇÕES LEGAIS E COMERCIAIS",
          body: "Ligar um espaço de trabalho pode envolver credenciais do Sentry, identificadores de dispositivos e dados de incidentes controlados pelo cliente. Isso cria responsabilidades sérias de segurança, privacidade, apoio e contrato. O Sentinel é, por isso, um complemento de melhor esforço para conhecimento e triagem, não um pager garantido, monitor primário ou sistema autónomo de resposta a incidentes.",
        },
        {
          tag: "PORQUE AINDA NÃO FOI LANÇADO",
          body: "O principal bloqueio ao lançamento não é uma funcionalidade em falta. É a responsabilidade pessoal. Não estou disposto a aceitar clientes enquanto uma notificação perdida, uma falha de segurança ou um incidente de dados me puder expor directamente. O lançamento exige uma entidade jurídica adequada, seguro apropriado e protecções revistas por juristas antes de ser responsável assumir esse risco.",
        },
      ],
    },
    honesty:
      "Esta página não apresenta métricas, clientes ou receitas inventados. Os números chegam quando existirem.",
  },
  sdlc: {
    kicker: "SDLC COM AGENTES",
    title: "Desenhar o Fluxo de Engenharia",
    intro:
      'Desenvolvimento com agentes não é "pedir à IA para construir a aplicação". É o desenho deliberado de contexto, restrições, permissões, ciclos de feedback, pontos de controlo, verificação independente, regras de escalada e responsabilidade ao longo de todo o ciclo de vida, sem abdicar do critério de engenharia.',
    selector: "O CICLO DE VIDA COMO SISTEMA LIGADO · SELECCIONE UMA FASE",
    responsibility: "QUEM DETÉM A RESPONSABILIDADE NESTA FASE",
    actors: [
      "HUMANO",
      "AGENTE DE IMPLEMENTAÇÃO",
      "AGENTE DE REVISÃO",
      "AGENTE DE PESQUISA",
      "TESTES / VALIDAÇÃO",
      "CI/CD E PRODUÇÃO",
    ],
    stages: [
      { label: "DESCOBERTA", name: "Descoberta", detail: "Enquadrar o problema antes de qualquer agente o ver. Os agentes ajudam a analisar trabalho anterior e concorrentes; a decisão sobre o que merece ser construído permanece humana.", weights: [3, 0, 0, 2, 0, 0] },
      { label: "REQUISITOS", name: "Requisitos", detail: "Os agentes redigem e testam os requisitos contra casos limite; o humano é responsável pelas prioridades e pela definição de concluído.", weights: [3, 1, 1, 2, 0, 0] },
      { label: "PESQUISA", name: "Pesquisa", detail: "O agente de pesquisa explora bibliotecas, padrões e restrições numa sandbox. Os resultados são pistas, não factos, até serem verificados.", weights: [1, 0, 1, 3, 0, 0] },
      { label: "ARQUITECTURA", name: "Arquitectura", detail: "Os agentes propõem e criticam estruturas; o humano escolhe, porque a arquitectura é onde os agentes optimizam localmente com mais confiança.", weights: [3, 1, 2, 1, 0, 0] },
      { label: "PLANEAMENTO", name: "Planeamento", detail: "O trabalho é decomposto em passos adequados a agentes, verificáveis de forma independente, com permissões e condições de paragem explícitas.", weights: [3, 2, 1, 0, 0, 0] },
      { label: "CÓDIGO", name: "Código", detail: "O agente principal de implementação trabalha num contexto delimitado, com ficheiros nomeados que pode alterar. Tudo o resto fica fora de alcance por defeito.", weights: [1, 3, 0, 0, 1, 0] },
      { label: "TESTES", name: "Testes", detail: "Os testes são escritos ou aprovados antes da implementação quando o risco o justifica; um ciclo separado valida em vez de confiar no agente autor.", weights: [1, 1, 1, 0, 3, 1] },
      { label: "REVISÃO", name: "Revisão", detail: "Um agente de revisão independente, sem memória da conversa de implementação, lê o diff a frio. O humano arbitra os desacordos.", weights: [2, 0, 3, 0, 1, 0] },
      { label: "DEPURAÇÃO", name: "Depuração", detail: "Reprodução antes da reparação: nenhuma correcção é aceite até a falha ser demonstrada e depois demonstrada como corrigida.", weights: [2, 2, 1, 1, 2, 0] },
      { label: "SEGURANÇA", name: "Segurança", detail: "Os agentes analisam e sugerem; um humano e ferramentas determinísticas detêm o julgamento final. É uma área onde os agentes falham em silêncio.", weights: [3, 0, 2, 1, 2, 1] },
      { label: "DOCUMENTAÇÃO", name: "Documentação", detail: "A documentação funciona também como contexto executável para futuras sessões de agentes, escrita tanto para o próximo agente como para o próximo humano.", weights: [1, 2, 1, 0, 0, 0] },
      { label: "PUBLICAÇÃO", name: "Publicação", detail: "Pipelines determinísticos, não agentes, movem o código. Os agentes preparam notas de versão e verificações de prontidão; o CI/CD guarda as chaves.", weights: [2, 0, 0, 0, 1, 3] },
      { label: "MONITORIZAÇÃO", name: "Monitorização", detail: "O feedback da produção fecha o ciclo. Erros e métricas tornam-se contexto estruturado que regressa ao planeamento.", weights: [2, 0, 0, 1, 1, 3] },
      { label: "MANUTENÇÃO", name: "Manutenção", detail: "Actualizações de dependências e pequenas correcções são o território mais seguro para agentes: delimitado, verificável e reversível.", weights: [1, 3, 1, 0, 2, 1] },
      { label: "RETROSPECTIVAS", name: "Retrospectivas", detail: "O que fizeram os agentes de errado e era previsível? Os padrões de falha alimentam a biblioteca de fluxos.", weights: [3, 0, 1, 1, 0, 1] },
    ],
    failuresTitle: "ONDE OS AGENTES FALHAM",
    failuresIntro:
      "O fluxo existe porque estes modos de falha são previsíveis. Cada um é um percurso terminado na lattice: observado, nomeado e considerado no desenho.",
    mitigation: "MITIGAÇÃO",
    flipFor: "Virar para ver a mitigação",
    flipBack: "Voltar",
    failures: [
      { name: "Invenção confiante", problem: "APIs, opções e comportamentos que nunca existiram, apresentados com total certeza.", fix: "Verificar em fontes reais: documentação, código e sistemas em execução, nunca na memória do agente. Alegações sem evidência são pistas, não factos." },
      { name: "Arquitectura superficial", problem: "Estruturas que satisfazem o pedido mas ignoram o sistema à sua volta.", fix: "Revisão arquitectural adversarial antes de qualquer código: um segundo agente, ou o humano, ataca a proposta até esta considerar o sistema completo." },
      { name: "Optimização local", problem: "Melhorar o ficheiro à custa da base de código.", fix: "Âmbito explícito em cada tarefa, mais um revisor instruído a ler para além do diff e a verificar os consumidores do que mudou." },
      { name: "Perda de contexto", problem: "Sessões longas esquecem silenciosamente restrições anteriores.", fix: "Sessões curtas e delimitadas com documentos de passagem deliberados. Comprimir o contexto de propósito antes de o agente o perder por acidente." },
      { name: "Reescritas desnecessárias", problem: "Reescrever código funcional porque reescrever é mais fácil do que ler.", fix: "Permissões de escrita apenas em ficheiros nomeados. Tudo o resto é só de leitura por defeito. Uma reescrita tem de ser pedida, nunca presumida." },
      { name: "Verificação incompleta", problem: '"Os testes passam" porque foram enfraquecidos até passarem.', fix: "Validação independente que o agente autor não pode alterar: execuções de testes separadas, ficheiros de teste protegidos e um revisor que também analisa o diff dos testes." },
      { name: "Uso excessivo de ferramentas", problem: "Dez chamadas a ferramentas quando uma pesquisa bastaria: custo, ruído e latência.", fix: "Observar os rastos regularmente e simplificar o fluxo. Dar aos agentes atalhos determinísticos mais baratos e instruções sobre quando os usar." },
      { name: "Acoplamento escondido", problem: "Alterações que funcionam localmente e quebram um consumidor que ninguém mencionou.", fix: "Documentação de integração no repositório e mapas de dependências como contexto permanente, para cada sessão saber o que depende de quê antes de editar." },
      { name: "Erros de segurança", problem: "Segredos nos registos, valores permissivos por defeito e construção de strings vulnerável a injecções.", fix: "Análise determinística e revisão humana em todas as alterações relevantes para segurança. A auto-avaliação do agente nunca é aceite como evidência." },
      { name: "Concordar com pressupostos errados", problem: "O utilizador está errado e o agente avança educadamente na mesma.", fix: "Um passo explícito de desafio cuja única função é discordar: um agente instruído a encontrar o que está errado, não a ser prestável." },
    ],
  },
  workflows: {
    kicker: "FLUXOS",
    title: "Padrões de Operação para Agentes",
    intro:
      "Uma biblioteca de padrões reutilizáveis. Cada padrão define o problema, o encaminhamento do trabalho entre humano e agentes, como o resultado é validado e, igualmente importante, quando não deve ser usado.",
    featureLabel: "PADRÃO 01 · DESENVOLVIDO EM PROFUNDIDADE",
    featureTitle: "Pesquisa → Plano → Desafio → Implementação → Revisão",
    stages: ["PESQUISA", "PLANO", "DESAFIO", "IMPLEMENTAÇÃO", "REVISÃO"],
    fields: [
      { tag: "PROBLEMA", body: "Os agentes produzem código plausível de imediato, o que torna tentador saltar o raciocínio. Planos sem desafio incorporam pressupostos errados que surgem mais tarde como retrabalho dispendioso." },
      { tag: "FLUXO", body: "Um agente de pesquisa explora o território. Uma passagem de planeamento produz um plano faseado. Um agente separado, ou o mesmo agente com instruções adversariais, ataca o plano. Só um plano sobrevivente chega à implementação. Um revisor a frio lê o diff final." },
      { tag: "RESPONSABILIDADE HUMANA", body: "Enquadrar o problema, julgar a ronda de desafio, arbitrar desacordos, aprovar o plano e assumir a integração. O humano é a constante em todas as fases." },
      { tag: "RESPONSABILIDADE DO AGENTE", body: "Amplitude de pesquisa, redacção do plano, crítica adversarial, implementação dentro do âmbito e revisão independente sem contexto prévio." },
      { tag: "VALIDAÇÃO", body: "A ronda de desafio valida o plano; os testes e a revisão independente validam o código. Nada é integrado apenas com a palavra do implementador." },
      { tag: "RISCOS", body: "Cerimónia em tarefas triviais; rondas de desafio que se transformam em concordância quando o crítico partilha o contexto do planeador; humanos que aprovam planos sobreviventes de forma automática." },
      { tag: "QUANDO NÃO USAR", body: "Alterações pequenas, reversíveis e bem compreendidas. Uma correcção de uma linha não precisa de um pipeline de cinco fases. É para isso que servem os padrões de manutenção." },
    ],
    notWhen: "NÃO USAR QUANDO",
    patterns: [
      { number: "02", name: "Separação Arquitecto / Construtor", problem: "Um agente que desenha e implementa defende o seu próprio desenho. Separar os papéis mantém a estrutura honesta.", notWhen: "A estrutura já está fixada e o trabalho apenas preenche uma forma conhecida." },
      { number: "03", name: "Agente independente de revisão de código", problem: "Um revisor sem memória da implementação lê o diff a frio e apresenta conclusões antes de qualquer revisão humana.", notWhen: "Código descartável gerado que nunca chegará à produção." },
      { number: "04", name: "Ciclo de agente orientado por testes", problem: "Testes escritos e aprovados antes da implementação dão ao agente um alvo objectivo e ao humano uma âncora de verificação.", notWhen: "Trabalho exploratório onde o comportamento desejado ainda está a ser descoberto." },
      { number: "05", name: "Reprodução do erro antes da reparação", problem: 'Nenhuma correcção é aceite até a falha ser demonstrada e depois demonstrada como corrigida. Elimina o "agora deve funcionar".', notWhen: "Falhas verdadeiramente não determinísticas. Nesse caso, o padrão muda primeiro para instrumentação." },
      { number: "06", name: "Documentação como contexto executável", problem: "Documentação escrita para uma sessão nova de agente poder agir: material de integração testado, não presumido.", notWhen: "Protótipos em rápida mudança onde a documentação ficaria imediatamente desactualizada." },
      { number: "07", name: "Integração no repositório", problem: "Uma primeira sessão estruturada que mapeia a base de código, convenções e acoplamentos antes de qualquer agente poder alterá-la.", notWhen: "Repositórios suficientemente pequenos para caberem numa única janela de contexto." },
      { number: "08", name: "Compressão de contexto e passagem", problem: "Tarefas longas são divididas entre sessões com documentos de passagem deliberados, porque a perda de contexto é silenciosa e cumulativa.", notWhen: "Tarefas que terminam confortavelmente numa única sessão focada." },
    ],
  },
  automation: {
    kicker: "AUTOMAÇÃO",
    title: "Remover a Repetição",
    intro:
      "Scripts, ferramentas e pequenos sistemas que eliminam trabalho repetitivo de engenharia. Duas regras governam tudo: a automação é um contínuo e nem todas as tarefas merecem um agente. Um script determinístico é muitas vezes mais barato, mais seguro e melhor.",
    continuum: [
      { label: "MANUAL", body: "Feito à mão. A escolha certa por defeito para tudo o que acontece menos de três vezes." },
      { label: "ASSISTIDO", body: "Um humano conduz; ferramentas ou um agente aceleram a parte intermédia e aborrecida." },
      { label: "COM SCRIPT", body: "Determinístico, versionado, passível de revisão. O nível de trabalho principal: a maioria das tarefas deve parar aqui." },
      { label: "OPERADO POR AGENTE", body: "Um agente executa um procedimento que ocasionalmente exige julgamento a meio." },
      { label: "CONDICIONALMENTE AUTÓNOMO", body: "Executa sem supervisão dentro de limites rígidos, com regras de escalada e um interruptor de emergência. Conquistado, nunca presumido." },
    ],
    items: [
      { name: "Análise de repositório", tier: "OPERADO POR AGENTE", body: "Mapeia estrutura, convenções e acoplamentos num guia de integração para humanos e sessões de agentes." },
      { name: "Validação de ambiente", tier: "COM SCRIPT", body: "Um comando que prova que um ambiente de desenvolvimento está realmente completo antes de começar o trabalho." },
      { name: "Orquestração de testes", tier: "COM SCRIPT", body: "Selecciona e executa o subconjunto certo de testes para cada alteração, com execuções completas reservadas para integrações." },
      { name: "Verificações de publicação", tier: "COM SCRIPT", body: "Verificação antes e depois da publicação. Determinística de propósito: não é desejado julgamento nesta fase." },
      { name: "Monitorização de dependências", tier: "OPERADO POR AGENTE", body: "Acompanha actualizações e avisos, prepara ramos de actualização e reúne a evidência para uma decisão humana." },
      { name: "Geração de documentação", tier: "OPERADO POR AGENTE", body: "Mantém o contexto executável actualizado a partir do código e do histórico de commits, com amostragem humana." },
      { name: "Regressão visual", tier: "COM SCRIPT", body: "Comparações de capturas nos fluxos principais. Baratas, simples e capazes de detectar o que os testes unitários estruturalmente não conseguem." },
      { name: "Triagem de incidentes", tier: "OPERADO POR AGENTE", body: "Agrupa, elimina duplicados e enriquece incidentes recebidos; a prioridade continua a ser uma decisão humana." },
      { name: "Passagens entre agentes", tier: "OPERADO POR AGENTE", body: "Gera documentos de contexto comprimido quando uma tarefa tem de atravessar fronteiras de sessão." },
      { name: "Relatórios operacionais", tier: "COM SCRIPT", body: "Resumos semanais da saúde da plataforma reunidos a partir de registos e métricas. Um cron job, não um agente." },
    ],
  },
  tooling: {
    kicker: "FERRAMENTAS DE IA",
    title: "Valor por Subscrição",
    intro:
      'Obter o máximo do Codex, Claude e subscrições semelhantes sem devoção a marcas. A pergunta útil não é "qual é o melhor modelo", mas que papel desempenha cada ferramenta num fluxo e quando um script local torna toda a pergunta irrelevante.',
    selector: "PAPÉIS, NÃO CLASSIFICAÇÕES · SELECCIONE UM PAPEL",
    discipline: "DISCIPLINA",
    roles: [
      { label: "EXPLORADOR", name: "Explorador", body: "Analisa território desconhecido: bases de código, bibliotecas, APIs e trabalho anterior. Optimizado para amplitude e iteração barata, não para correcção.", discipline: "Tudo o que o explorador relata é uma pista até ser verificado. Nunca deixe o resultado da exploração seguir directamente para implementação." },
      { label: "ARQUITECTO", name: "Arquitecto", body: "Propõe estruturas, interfaces e compromissos. Funciona melhor de forma adversarial: um arquitecto propõe, outro desafia.", discipline: "O humano escolhe. Os agentes defendem a arquitectura que geraram primeiro." },
      { label: "IMPLEMENTADOR", name: "Implementador", body: "Escreve código dentro de um contexto delimitado: ficheiros nomeados, permissões explícitas e um plano que já sobreviveu a um desafio.", discipline: "O âmbito é a superfície de controlo. Um implementador com acesso de escrita a todo o repositório é uma responsabilidade, não um ganho de produtividade." },
      { label: "REVISOR", name: "Revisor", body: "Lê diffs a frio, sem memória da conversa de implementação, e apresenta conclusões de forma independente.", discipline: "A independência é todo o valor. Um revisor que partilha contexto com o implementador limita-se a concordar." },
      { label: "DEPURADOR", name: "Depurador", body: "Reproduz falhas, forma hipóteses e testa-as uma de cada vez. Reprodução antes da reparação, sempre.", discipline: 'Recusar correcções para erros que nunca foram demonstrados. "Agora deve funcionar" não é evidência.' },
      { label: "PARCEIRO DE DOCUMENTAÇÃO", name: "Parceiro de documentação", body: "Mantém a documentação como contexto executável: o material de integração que a próxima sessão de agente irá realmente consumir.", discipline: "Documentação sobre a qual um agente não consegue agir é decoração. Teste-a ao iniciar uma sessão nova apenas com essa documentação." },
      { label: "OPERADOR DE NAVEGADOR", name: "Operador de navegador", body: "Controla um navegador real para verificar fluxos, formulários, estados visuais e regressões que um teste unitário não consegue ver.", discipline: "Usar para verificação, não para descoberta. É lento e caro por conclusão." },
      { label: "EXECUTOR DE AUTOMAÇÃO", name: "Executor de automação", body: "Executa procedimentos com script onde ocasionalmente pode ser necessário julgamento durante a execução.", discipline: "Se nunca for necessário julgamento, elimine o agente e mantenha o script." },
    ],
    designer: "DESENHADOR DE FLUXO · UMA FERRAMENTA CONCEPTUAL",
    caveat:
      "Ajuste as características de uma tarefa; a recomendação descreve a forma do fluxo, não preços nem capacidades. Onde fossem necessários dados em tempo real, a ferramenta permanece deliberadamente conceptual. Confirme os limites actuais das subscrições antes de depender de qualquer pressuposto de custo.",
    sliderLabels: ["COMPLEXIDADE", "RISCO", "REPETIÇÃO", "SENSIBILIDADE AO CUSTO", "VERIFICAÇÃO NECESSÁRIA"],
    levels: ["MÍNIMO", "BAIXO", "MODERADO", "ALTO", "CRÍTICO"],
    recommendation: "FORMA RECOMENDADA",
    recommendations: {
      script: { title: "Script determinístico", lines: ["Muita repetição com baixa complexidade e baixo risco é território de scripts. Um agente acrescenta aqui custo e não determinismo.", "Escreva uma vez, versione e deixe o CI executar."] },
      highRisk: { title: "Ancorado num humano, vários agentes e controlos", lines: ["Risco alto exige verificação independente: agentes separados de implementação e revisão, sem contexto partilhado.", "Insira aprovações humanas explícitas antes de qualquer acção irreversível."], validation: "Acrescente ferramentas de validação determinísticas: testes e análise estática como terceira verificação não negociável." },
      complex: { title: "Pesquisa → Plano → Desafio → Implementação → Revisão", lines: ["Alta complexidade justifica o padrão completo: pesquisa primeiro, seguida de um plano que tem de sobreviver a um desafio adversarial antes do código.", "Decomponha em passos verificáveis de forma independente para manter o contexto controlável."] },
      moderate: { title: "Um agente, contexto delimitado", lines: ["Tarefa moderada: um agente de implementação com ficheiros nomeados, uma definição clara de concluído e uma revisão humana rápida."] },
      cost: "Sensível ao custo: encaminhe a pesquisa para modelos mais baratos e reserve o modelo mais forte para o passo onde a qualidade realmente se acumula.",
      repetition: "A repetição é alta. Depois da segunda execução manual, extraia as partes estáveis para um script e reduza o papel do agente.",
    },
  },
  lab: {
    kicker: "LABORATÓRIO",
    title: "Experiências em Curso",
    intro: "Inacabado por desenho. As experiências abandonadas permanecem visíveis. Saber quando parar faz parte do método.",
    items: [
      { status: "EM TESTE", tone: "cyan", name: "Harness de revisão sem contexto", body: "Ferramentas que iniciam um agente revisor sem contexto de implementação e comparam as conclusões com a revisão humana. A medir onde a independência realmente compensa." },
      { status: "EM PROTÓTIPO", tone: "cyan", name: "Compressor de passagem", body: "Transforma uma longa sessão de agente num documento mínimo de contexto a partir do qual uma sessão nova consegue retomar. A parte difícil é decidir o que esquecer." },
      { status: "EM INVESTIGAÇÃO", tone: "muted", name: "Visibilidade em motores de resposta", body: "Como páginas locais programáticas surgem nos motores de resposta de IA face à pesquisa clássica. Fase inicial, sobretudo desenho de medição." },
      { status: "EM PAUSA", tone: "amber", name: "Regressão visual através de agente de navegador", body: "Um agente a operar um navegador para verificações de regressão. Em pausa: um script de comparação de capturas faz 90% do trabalho por 5% do custo." },
      { status: "ABANDONADO", tone: "muted", discarded: true, name: "Actualizações de dependências totalmente autónomas", body: "Abandonado depois de dois quase-incidentes. Actualizações que passam os testes podem alterar comportamentos nunca cobertos. Agora são preparadas pelo agente e integradas pelo humano." },
      { status: "PUBLICADO", tone: "cyan", name: "Diagnóstico de ambiente", body: "Um único script que valida uma configuração local completa e indica exactamente o que falta. Aborrecido e usado todas as semanas." },
    ],
  },
  notes: {
    categoriesLabel: "Categorias",
    kicker: "NOTAS DE CAMPO",
    title: "O Que o Trabalho Ensina",
    intro: "Escrita que se acumula em vez de simplesmente passar. Cada nota está ligada ao sistema ou fluxo que lhe deu origem. Siga uma nota de volta à origem e o percurso acende-se.",
    categories: ["ENGENHARIA COM AGENTES", "ARQUITECTURA DE SOFTWARE", "AUTOMAÇÃO", "CONSTRUÇÃO DE PRODUTOS", "ECONOMIA DA IA", "ANÁLISE DE FALHAS", "EXPERIÊNCIAS PRÁTICAS", "CARREIRA E OFÍCIO"],
    items: [
      { title: "O agente mais barato é um script bash", category: "ECONOMIA DA IA", origin: "AUTOMAÇÃO", target: "automation", body: "Onde o contínuo da automação realmente compensa: substituir um ciclo de agente por quarenta linhas de shell determinístico e como reconhecer as tarefas onde isso é verdade." },
      { title: "O que uma ronda de desafio detecta", category: "ENGENHARIA COM AGENTES", origin: "FLUXOS", target: "workflows", body: "Um mês a registar cada plano que falhou a revisão adversarial: pressupostos errados sobre a forma dos dados dominam; APIs alucinadas são menos frequentes do que se esperava." },
      { title: "Páginas programáticas sem spam", category: "CONSTRUÇÃO DE PRODUTOS", origin: "FOUNDMYPRO", target: "systems", body: "Os limiares de qualidade que mantêm páginas locais geradas genuinamente úteis e o que aconteceu às que ficaram abaixo do nível exigido." },
      { title: "Dois quase-incidentes com actualizações autónomas", category: "ANÁLISE DE FALHAS", origin: "LABORATÓRIO", target: "lab", body: 'A experiência de actualização de dependências que foi abandonada: o que os testes não viram e porque "verde" não significava "seguro".' },
      { title: "Porque o Sentinel ainda não foi lançado", category: "CONSTRUÇÃO DE PRODUTOS", origin: "SENTINEL", target: "systems", body: "Responsabilidade, confiança e a disciplina de adiar um produto cujos modos de falha afectam o sistema de produção de outra pessoa." },
      { title: "Do serviço de sala ao desenho de sistemas", category: "CARREIRA E OFÍCIO", origin: "SOBRE", target: "about", body: "O que as operações de hotelaria ensinam sobre software: os padrões revelam-se no comportamento sob pressão e todos os sistemas são julgados no seu pior momento." },
    ],
  },
  about: {
    kicker: "SOBRE",
    title: "O Engenheiro por Trás do Sistema",
    paragraphs: [
      "Engenheiro de software com experiência em aplicações empresariais, a construir produtos em paralelo e a tratar o desenvolvimento assistido por IA como disciplina de engenharia, não como atalho.",
      "Antes do software: anos a liderar operações de hotelaria. Essa experiência continua presente: serviço como padrão e não como slogan, calma sob pressão e atenção aos detalhes operacionais que decidem se um sistema funciona realmente para quem o utiliza.",
      "O foco actual é o desenvolvimento de software com agentes: desenhar o contexto, as restrições e a verificação à volta de agentes de IA para que a sua velocidade se transforme em resultado fiável. Os produtos deste site são onde esses métodos são testados contra a realidade.",
    ],
    preference: "Preferência: sistemas úteis em vez de demonstrações. Se não corre em produção, é uma hipótese.",
  },
  contact: {
    kicker: "CONTACTO",
    title: "Abrir uma Ligação",
    intro: "Uma mensagem cria um novo nó na lattice. Escolha a aresta a que se deve ligar ou escreva simplesmente.",
    routes: [
      { name: "Funções de engenharia", body: "Posições sénior de engenharia onde os fluxos com agentes e o pensamento de produto sejam relevantes.", subject: "Função de engenharia" },
      { name: "Colaboração de produto", body: "Está a construir algo real e procura um parceiro com pensamento de sistemas.", subject: "Colaboração de produto" },
      { name: "Discussão técnica", body: "SDLC com agentes, desenho de fluxos e economia da automação. Discordância bem-vinda.", subject: "Discussão técnica" },
      { name: "Feedback de projecto", body: "Usou o FoundMyPro ou leu uma nota de campo e encontrou algo errado ou em falta.", subject: "Feedback de projecto" },
      { name: "Palestras ou escrita", body: "Palestras ou artigos sobre desenvolvimento com agentes, contados a partir da prática e não do entusiasmo vazio.", subject: "Palestras ou escrita" },
    ],
    replyNote: "respostas dentro de alguns dias, com prioridades honestas.",
  },
};
